In [1]:
cd ..

/home/janek/reasonable-embeddings


In [2]:
import numpy as np
import pandas as pd
import torch as T
import torch.nn.functional as F
import torch.nn as nn
import random
from sklearn import metrics
from src.reasoner_mod import *
from src.generate import load_dataset, prepare_data, count_elements, reduce_dataset, make_dataset
from src.reasoner import *
from src.utils import *
from src.vis import *


In [3]:
seed = 2022
dataset_path = 'local/out/dataset/sub-100.json'
ts = timestr()
train_onto, test_onto, data_tr, data_vl, data_te = load_dataset(dataset_path)
rng = np.random.default_rng(seed)

In [4]:
data_tr, data_vl, data_te_tr, data_te_vl, idx_te_te, X_te_te, y_te_te = prepare_data(data_tr, data_vl, data_te, seed, 5)

In [5]:
for i, onto in enumerate(train_onto):
    fact = Reasoner.from_onto(onto, timeout=None)
    queries, answers = make_dataset(onto, fact, rng, 400 - data_vl[0].count(i), 6 , 9)
    data_vl[1].extend(queries)
    data_vl[0].extend(len(queries)*[i])
    data_vl[2].extend(answers)

FaCT++.Kernel: Reasoner for the SROIQ(D) Description Logic, 64-bit
Copyright (C) Dmitry Tsarkov, 2002-2017. Version 1.7.0-SNAPSHOT (01 January 2017)


In [6]:
data_tr = reduce_dataset(data_tr, len(train_onto), 1600, data_vl)

In [7]:
print(np.mean(data_tr[2]))
print(np.mean(data_vl[2]))
print()
print(np.mean(data_te_tr[2]))
print(np.mean(data_te_vl[2]))
print(np.mean(y_te_te))

0.19665625
0.1984375

0.2203348305430788
0.18243243243243243
0.18631643249847282


In [8]:
emb_size = 10
hidden_size = 16
epoch_count = 10
test_epoch_count = 10
batch_size = 32

T.manual_seed(seed)
trained_reasoner = ModifiedReasonerHead(emb_size=emb_size, hidden_size=hidden_size)
encoders = [ModifiedEmbeddingLayer.from_onto(onto, emb_size=emb_size) for onto in train_onto]

print(f'created reasoner with {paramcount(trained_reasoner)} parameters')
print(f'created {len(encoders)} encoders with {paramcount(encoders[0])} parameters each')
# train_logger = train_mod(data_tr, data_vl, trained_reasoner, encoders, epoch_count=epoch_count,
                        #   batch_size=batch_size, identities_weight=0.02, identitity_weight_decay=0.96)

created reasoner with 3283 parameters
created 40 encoders with 1270 parameters each


In [9]:
import optuna
from sklearn.metrics import precision_recall_curve, roc_auc_score, accuracy_score
from sklearn.metrics import auc

def objective(trial):
    T.manual_seed(seed)
    random.seed(seed)
    trained_reasoner = ModifiedReasonerHead(emb_size=emb_size, hidden_size=hidden_size)
    encoders = [ModifiedEmbeddingLayer.from_onto(onto, emb_size=emb_size) for onto in train_onto]

    id_weight = trial.suggest_int('identity_weight', 10, 100)
    decay= trial.suggest_int('decay',900, 999)

    id_weight/=1000
    decay/=1000
    y, Y = train_mod(data_tr, data_vl, trained_reasoner, encoders, epoch_count=15,
                            batch_size=batch_size, identities_weight=id_weight, identitity_weight_decay=decay)
    
    prec, rec, _ = precision_recall_curve(y, Y)
    
    print('prc: ', auc(rec, prec))
    print('roc: ', roc_auc_score(y,Y))
    K = np.array(Y) > 0.5
    print('acc: ',accuracy_score(y,K))

    return auc(rec, prec)*10 + roc_auc_score(y,Y)*6 + accuracy_score(y,K)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

# Wyświetl najlepsze hiperparametry oraz wartość dokładności
print('Najlepsze hiperparametry:')
print(study.best_params)
print('Wartość średniej dokładności dla najlepszych hiperparametrów:')
print(study.best_value)

[I 2024-07-29 21:50:52,988] A new study created in memory with name: no-name-883fadcc-5f90-4742-8e3c-3ef21fc99c24


train epoch 00/15 | batch 2001/2000 | loss 1.2986 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 27.21s
train epoch 01/15 | batch 2001/2000 | loss 0.9129 | val loss 0.4752 | acc 0.8279 | f1 0.3493 | prec 0.6998 | recall 0.2328 | roc auc 0.6655 | pr auc 0.4696 | elapsed 84.20s
train epoch 02/15 | batch 2001/2000 | loss 0.5503 | val loss 0.4013 | acc 0.8436 | f1 0.5136 | prec 0.6709 | recall 0.4161 | roc auc 0.7757 | pr auc 0.6049 | elapsed 90.90s
train epoch 03/15 | batch 2001/2000 | loss 0.3791 | val loss 0.3795 | acc 0.8581 | f1 0.6008 | prec 0.6802 | recall 0.5380 | roc auc 0.8182 | pr auc 0.6808 | elapsed 90.42s
train epoch 04/15 | batch 2001/2000 | loss 0.2598 | val loss 0.3593 | acc 0.8699 | f1 0.6508 | prec 0.6961 | recall 0.6110 | roc auc 0.8467 | pr auc 0.7326 | elapsed 90.20s
train epoch 05/15 | batch 2001/2000 | loss 0.1995 | val loss 0.3371 | acc 0.8784 | f1 0.6807 | prec 0.7105 | recall 0.6532 | roc auc 0.

[I 2024-07-29 22:13:39,811] Trial 0 finished with value: 15.237173928131474 and parameters: {'identity_weight': 36, 'decay': 959}. Best is trial 0 with value: 15.237173928131474.


train epoch 15/15 | batch 2001/2000 | loss 0.0820 | val loss 0.2982 | acc 0.9043 | f1 0.7661 | prec 0.7439 | recall 0.7896 | roc auc 0.9324 | pr auc 0.8739 | elapsed 88.69s
prc:  0.8738663923872139
roc:  0.9323662507098893
acc:  0.9043125
train epoch 00/15 | batch 2001/2000 | loss 1.9233 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 31.10s
train epoch 01/15 | batch 2001/2000 | loss 1.2448 | val loss 0.4777 | acc 0.8234 | f1 0.3712 | prec 0.6328 | recall 0.2627 | roc auc 0.6686 | pr auc 0.4714 | elapsed 88.88s
train epoch 02/15 | batch 2001/2000 | loss 0.6995 | val loss 0.4065 | acc 0.8401 | f1 0.5185 | prec 0.6439 | recall 0.4340 | roc auc 0.7736 | pr auc 0.6029 | elapsed 89.19s
train epoch 03/15 | batch 2001/2000 | loss 0.4614 | val loss 0.3842 | acc 0.8546 | f1 0.6040 | prec 0.6569 | recall 0.5591 | roc auc 0.8173 | pr auc 0.6810 | elapsed 88.55s
train epoch 04/15 | batch 2001/2000 | loss 0.2852 | val loss 0.3639 |

[I 2024-07-29 22:36:35,320] Trial 1 finished with value: 15.179041723223886 and parameters: {'identity_weight': 79, 'decay': 909}. Best is trial 0 with value: 15.237173928131474.


roc:  0.9298806280793848
acc:  0.9005625
train epoch 00/15 | batch 2001/2000 | loss 1.4294 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 31.41s
train epoch 01/15 | batch 2001/2000 | loss 0.9755 | val loss 0.4764 | acc 0.8273 | f1 0.3557 | prec 0.6843 | recall 0.2403 | roc auc 0.6660 | pr auc 0.4697 | elapsed 88.35s
train epoch 02/15 | batch 2001/2000 | loss 0.5742 | val loss 0.4021 | acc 0.8433 | f1 0.5155 | prec 0.6667 | recall 0.4202 | roc auc 0.7756 | pr auc 0.6052 | elapsed 90.49s
train epoch 03/15 | batch 2001/2000 | loss 0.3880 | val loss 0.3801 | acc 0.8579 | f1 0.6023 | prec 0.6776 | recall 0.5420 | roc auc 0.8183 | pr auc 0.6813 | elapsed 87.28s
train epoch 04/15 | batch 2001/2000 | loss 0.2589 | val loss 0.3592 | acc 0.8691 | f1 0.6496 | prec 0.6930 | recall 0.6113 | roc auc 0.8469 | pr auc 0.7333 | elapsed 89.97s
train epoch 05/15 | batch 2001/2000 | loss 0.1984 | val loss 0.3369 | acc 0.8780 | f1 0.6796 |

[I 2024-07-29 22:59:06,355] Trial 2 finished with value: 15.23796909768126 and parameters: {'identity_weight': 45, 'decay': 922}. Best is trial 2 with value: 15.23796909768126.


train epoch 15/15 | batch 2001/2000 | loss 0.0799 | val loss 0.2965 | acc 0.9058 | f1 0.7690 | prec 0.7491 | recall 0.7899 | roc auc 0.9321 | pr auc 0.8739 | elapsed 79.46s
prc:  0.8739340278668505
roc:  0.9321360531687924
acc:  0.9058125
train epoch 00/15 | batch 2001/2000 | loss 1.1098 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 31.44s
train epoch 01/15 | batch 2001/2000 | loss 0.8006 | val loss 0.4771 | acc 0.8291 | f1 0.3344 | prec 0.7355 | recall 0.2164 | roc auc 0.6594 | pr auc 0.4644 | elapsed 88.01s
train epoch 02/15 | batch 2001/2000 | loss 0.4969 | val loss 0.4008 | acc 0.8438 | f1 0.5023 | prec 0.6831 | recall 0.3972 | roc auc 0.7742 | pr auc 0.6017 | elapsed 90.66s
train epoch 03/15 | batch 2001/2000 | loss 0.3535 | val loss 0.3765 | acc 0.8601 | f1 0.5972 | prec 0.6968 | recall 0.5225 | roc auc 0.8167 | pr auc 0.6786 | elapsed 88.84s
train epoch 04/15 | batch 2001/2000 | loss 0.2601 | val loss 0.3552 |

[I 2024-07-29 23:22:03,622] Trial 3 finished with value: 15.293134819419421 and parameters: {'identity_weight': 23, 'decay': 952}. Best is trial 3 with value: 15.293134819419421.


train epoch 15/15 | batch 2001/2000 | loss 0.0789 | val loss 0.2885 | acc 0.9097 | f1 0.7764 | prec 0.7632 | recall 0.7899 | roc auc 0.9340 | pr auc 0.8779 | elapsed 88.49s
prc:  0.8779258600903972
roc:  0.9340314530859081
acc:  0.9096875
train epoch 00/15 | batch 2001/2000 | loss 1.5311 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 32.00s
train epoch 01/15 | batch 2001/2000 | loss 1.0297 | val loss 0.4758 | acc 0.8265 | f1 0.3604 | prec 0.6712 | recall 0.2463 | roc auc 0.6676 | pr auc 0.4709 | elapsed 86.92s
train epoch 02/15 | batch 2001/2000 | loss 0.5980 | val loss 0.4028 | acc 0.8432 | f1 0.5181 | prec 0.6639 | recall 0.4249 | roc auc 0.7755 | pr auc 0.6052 | elapsed 88.94s
train epoch 03/15 | batch 2001/2000 | loss 0.4018 | val loss 0.3807 | acc 0.8571 | f1 0.6031 | prec 0.6720 | recall 0.5471 | roc auc 0.8183 | pr auc 0.6816 | elapsed 87.54s
train epoch 04/15 | batch 2001/2000 | loss 0.2629 | val loss 0.3599 |

[I 2024-07-29 23:45:14,450] Trial 4 finished with value: 15.22213029474674 and parameters: {'identity_weight': 52, 'decay': 916}. Best is trial 3 with value: 15.293134819419421.


train epoch 00/15 | batch 2001/2000 | loss 1.4149 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 39.34s
train epoch 01/15 | batch 2001/2000 | loss 0.9848 | val loss 0.4761 | acc 0.8269 | f1 0.3562 | prec 0.6803 | recall 0.2413 | roc auc 0.6665 | pr auc 0.4700 | elapsed 101.94s
train epoch 02/15 | batch 2001/2000 | loss 0.5867 | val loss 0.4024 | acc 0.8436 | f1 0.5181 | prec 0.6668 | recall 0.4236 | roc auc 0.7757 | pr auc 0.6054 | elapsed 97.81s
train epoch 03/15 | batch 2001/2000 | loss 0.3972 | val loss 0.3813 | acc 0.8572 | f1 0.6031 | prec 0.6723 | recall 0.5468 | roc auc 0.8185 | pr auc 0.6811 | elapsed 99.80s
train epoch 04/15 | batch 2001/2000 | loss 0.2608 | val loss 0.3595 | acc 0.8681 | f1 0.6489 | prec 0.6878 | recall 0.6142 | roc auc 0.8472 | pr auc 0.7341 | elapsed 98.94s
train epoch 05/15 | batch 2001/2000 | loss 0.2020 | val loss 0.3377 | acc 0.8769 | f1 0.6785 | prec 0.7040 | recall 0.6548 | roc auc 0

[I 2024-07-30 00:11:25,857] Trial 5 finished with value: 15.204593539419049 and parameters: {'identity_weight': 44, 'decay': 967}. Best is trial 3 with value: 15.293134819419421.


roc:  0.9312555877883685
acc:  0.9009375
train epoch 00/15 | batch 2001/2000 | loss 1.6473 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 34.99s
train epoch 01/15 | batch 2001/2000 | loss 1.1124 | val loss 0.4762 | acc 0.8257 | f1 0.3657 | prec 0.6579 | recall 0.2532 | roc auc 0.6685 | pr auc 0.4715 | elapsed 99.79s
train epoch 02/15 | batch 2001/2000 | loss 0.6455 | val loss 0.4043 | acc 0.8424 | f1 0.5203 | prec 0.6572 | recall 0.4306 | roc auc 0.7751 | pr auc 0.6047 | elapsed 100.21s
train epoch 03/15 | batch 2001/2000 | loss 0.4345 | val loss 0.3826 | acc 0.8549 | f1 0.6017 | prec 0.6610 | recall 0.5521 | roc auc 0.8182 | pr auc 0.6815 | elapsed 100.09s
train epoch 04/15 | batch 2001/2000 | loss 0.2742 | val loss 0.3615 | acc 0.8661 | f1 0.6470 | prec 0.6782 | recall 0.6186 | roc auc 0.8474 | pr auc 0.7344 | elapsed 101.76s
train epoch 05/15 | batch 2001/2000 | loss 0.2049 | val loss 0.3398 | acc 0.8742 | f1 0.675

[I 2024-07-30 00:36:27,192] Trial 6 finished with value: 15.177847452562665 and parameters: {'identity_weight': 60, 'decay': 949}. Best is trial 3 with value: 15.293134819419421.


train epoch 15/15 | batch 2001/2000 | loss 0.0836 | val loss 0.3115 | acc 0.8992 | f1 0.7584 | prec 0.7231 | recall 0.7972 | roc auc 0.9301 | pr auc 0.8698 | elapsed 98.12s
prc:  0.8697865772887755
roc:  0.9301323632791514
acc:  0.8991875
train epoch 00/15 | batch 2001/2000 | loss 2.0686 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 34.74s
train epoch 01/15 | batch 2001/2000 | loss 1.3843 | val loss 0.4800 | acc 0.8207 | f1 0.3729 | prec 0.6093 | recall 0.2687 | roc auc 0.6679 | pr auc 0.4704 | elapsed 96.37s
train epoch 02/15 | batch 2001/2000 | loss 0.7946 | val loss 0.4099 | acc 0.8384 | f1 0.5212 | prec 0.6326 | recall 0.4431 | roc auc 0.7720 | pr auc 0.6002 | elapsed 97.43s
train epoch 03/15 | batch 2001/2000 | loss 0.5283 | val loss 0.3884 | acc 0.8502 | f1 0.5983 | prec 0.6393 | recall 0.5622 | roc auc 0.8166 | pr auc 0.6795 | elapsed 104.60s
train epoch 04/15 | batch 2001/2000 | loss 0.3101 | val loss 0.3695 

[I 2024-07-30 01:01:01,281] Trial 7 finished with value: 15.065128084426304 and parameters: {'identity_weight': 89, 'decay': 983}. Best is trial 3 with value: 15.293134819419421.


train epoch 00/15 | batch 2001/2000 | loss 1.4730 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 32.67s
train epoch 01/15 | batch 2001/2000 | loss 1.0270 | val loss 0.4758 | acc 0.8264 | f1 0.3596 | prec 0.6707 | recall 0.2457 | roc auc 0.6676 | pr auc 0.4708 | elapsed 89.49s
train epoch 02/15 | batch 2001/2000 | loss 0.6111 | val loss 0.4031 | acc 0.8429 | f1 0.5187 | prec 0.6618 | recall 0.4265 | roc auc 0.7757 | pr auc 0.6053 | elapsed 92.07s
train epoch 03/15 | batch 2001/2000 | loss 0.4143 | val loss 0.3821 | acc 0.8559 | f1 0.6027 | prec 0.6657 | recall 0.5506 | roc auc 0.8185 | pr auc 0.6813 | elapsed 91.64s
train epoch 04/15 | batch 2001/2000 | loss 0.2668 | val loss 0.3606 | acc 0.8668 | f1 0.6470 | prec 0.6824 | recall 0.6151 | roc auc 0.8474 | pr auc 0.7344 | elapsed 91.72s
train epoch 05/15 | batch 2001/2000 | loss 0.2052 | val loss 0.3389 | acc 0.8759 | f1 0.6781 | prec 0.6985 | recall 0.6589 | roc auc 0.

[I 2024-07-30 01:24:37,728] Trial 8 finished with value: 15.16935182967373 and parameters: {'identity_weight': 48, 'decay': 986}. Best is trial 3 with value: 15.293134819419421.


prc:  0.869199765782679
roc:  0.9301006953078232
acc:  0.89675
train epoch 00/15 | batch 2001/2000 | loss 1.9669 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 33.29s
train epoch 01/15 | batch 2001/2000 | loss 1.2837 | val loss 0.4783 | acc 0.8231 | f1 0.3724 | prec 0.6287 | recall 0.2646 | roc auc 0.6685 | pr auc 0.4712 | elapsed 91.40s
train epoch 02/15 | batch 2001/2000 | loss 0.7248 | val loss 0.4075 | acc 0.8393 | f1 0.5182 | prec 0.6394 | recall 0.4356 | roc auc 0.7731 | pr auc 0.6021 | elapsed 93.53s
train epoch 03/15 | batch 2001/2000 | loss 0.4785 | val loss 0.3853 | acc 0.8529 | f1 0.6014 | prec 0.6503 | recall 0.5594 | roc auc 0.8171 | pr auc 0.6807 | elapsed 92.41s
train epoch 04/15 | batch 2001/2000 | loss 0.2920 | val loss 0.3653 | acc 0.8629 | f1 0.6441 | prec 0.6644 | recall 0.6249 | roc auc 0.8467 | pr auc 0.7338 | elapsed 90.74s
train epoch 05/15 | batch 2001/2000 | loss 0.2083 | val loss 0.3437 | ac

[I 2024-07-30 01:48:17,216] Trial 9 finished with value: 15.150729334816685 and parameters: {'identity_weight': 82, 'decay': 929}. Best is trial 3 with value: 15.293134819419421.


train epoch 00/15 | batch 2001/2000 | loss 0.9355 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 31.92s
train epoch 01/15 | batch 2001/2000 | loss 0.6965 | val loss 0.4817 | acc 0.8306 | f1 0.3008 | prec 0.8317 | recall 0.1836 | roc auc 0.6458 | pr auc 0.4508 | elapsed 91.91s
train epoch 02/15 | batch 2001/2000 | loss 0.4520 | val loss 0.4032 | acc 0.8437 | f1 0.4844 | prec 0.7011 | recall 0.3701 | roc auc 0.7692 | pr auc 0.5914 | elapsed 91.93s
train epoch 03/15 | batch 2001/2000 | loss 0.3310 | val loss 0.3774 | acc 0.8606 | f1 0.5858 | prec 0.7139 | recall 0.4967 | roc auc 0.8111 | pr auc 0.6698 | elapsed 90.78s
train epoch 04/15 | batch 2001/2000 | loss 0.2563 | val loss 0.3509 | acc 0.8748 | f1 0.6439 | prec 0.7392 | recall 0.5704 | roc auc 0.8407 | pr auc 0.7272 | elapsed 92.89s
train epoch 05/15 | batch 2001/2000 | loss 0.2076 | val loss 0.3311 | acc 0.8836 | f1 0.6807 | prec 0.7466 | recall 0.6255 | roc auc 0.

[I 2024-07-30 02:12:00,396] Trial 10 finished with value: 15.349425072967554 and parameters: {'identity_weight': 11, 'decay': 943}. Best is trial 10 with value: 15.349425072967554.


roc:  0.9352284262712776
acc:  0.9178125
train epoch 00/15 | batch 2001/2000 | loss 0.9645 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 33.56s
train epoch 01/15 | batch 2001/2000 | loss 0.7133 | val loss 0.4799 | acc 0.8308 | f1 0.3093 | prec 0.8145 | recall 0.1909 | roc auc 0.6498 | pr auc 0.4550 | elapsed 90.84s
train epoch 02/15 | batch 2001/2000 | loss 0.4585 | val loss 0.4024 | acc 0.8442 | f1 0.4892 | prec 0.6999 | recall 0.3761 | roc auc 0.7706 | pr auc 0.5941 | elapsed 92.49s
train epoch 03/15 | batch 2001/2000 | loss 0.3344 | val loss 0.3767 | acc 0.8604 | f1 0.5876 | prec 0.7103 | recall 0.5011 | roc auc 0.8126 | pr auc 0.6722 | elapsed 92.13s
train epoch 04/15 | batch 2001/2000 | loss 0.2575 | val loss 0.3508 | acc 0.8748 | f1 0.6462 | prec 0.7352 | recall 0.5764 | roc auc 0.8423 | pr auc 0.7291 | elapsed 91.85s
train epoch 05/15 | batch 2001/2000 | loss 0.2065 | val loss 0.3318 | acc 0.8828 | f1 0.6808 |

[I 2024-07-30 02:35:30,892] Trial 11 finished with value: 15.343634354686522 and parameters: {'identity_weight': 13, 'decay': 942}. Best is trial 10 with value: 15.349425072967554.


train epoch 00/15 | batch 2001/2000 | loss 0.9500 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 32.07s
train epoch 01/15 | batch 2001/2000 | loss 0.7047 | val loss 0.4808 | acc 0.8308 | f1 0.3057 | prec 0.8232 | recall 0.1877 | roc auc 0.6479 | pr auc 0.4529 | elapsed 89.63s
train epoch 02/15 | batch 2001/2000 | loss 0.4549 | val loss 0.4028 | acc 0.8438 | f1 0.4858 | prec 0.7001 | recall 0.3720 | roc auc 0.7699 | pr auc 0.5927 | elapsed 91.49s
train epoch 03/15 | batch 2001/2000 | loss 0.3325 | val loss 0.3771 | acc 0.8606 | f1 0.5867 | prec 0.7127 | recall 0.4986 | roc auc 0.8118 | pr auc 0.6710 | elapsed 92.03s
train epoch 04/15 | batch 2001/2000 | loss 0.2567 | val loss 0.3508 | acc 0.8749 | f1 0.6454 | prec 0.7374 | recall 0.5739 | roc auc 0.8415 | pr auc 0.7281 | elapsed 89.88s
train epoch 05/15 | batch 2001/2000 | loss 0.2070 | val loss 0.3313 | acc 0.8831 | f1 0.6807 | prec 0.7434 | recall 0.6277 | roc auc 0.

[I 2024-07-30 02:58:51,768] Trial 12 finished with value: 15.345941719001715 and parameters: {'identity_weight': 12, 'decay': 940}. Best is trial 10 with value: 15.349425072967554.


prc:  0.8818051545980581
roc:  0.9351587788368558
acc:  0.9169375
train epoch 00/15 | batch 2001/2000 | loss 0.9500 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 33.12s
train epoch 01/15 | batch 2001/2000 | loss 0.7048 | val loss 0.4808 | acc 0.8308 | f1 0.3057 | prec 0.8232 | recall 0.1877 | roc auc 0.6479 | pr auc 0.4530 | elapsed 89.10s
train epoch 02/15 | batch 2001/2000 | loss 0.4550 | val loss 0.4028 | acc 0.8438 | f1 0.4861 | prec 0.7002 | recall 0.3723 | roc auc 0.7699 | pr auc 0.5927 | elapsed 91.30s
train epoch 03/15 | batch 2001/2000 | loss 0.3326 | val loss 0.3771 | acc 0.8607 | f1 0.5870 | prec 0.7129 | recall 0.4989 | roc auc 0.8118 | pr auc 0.6710 | elapsed 92.00s
train epoch 04/15 | batch 2001/2000 | loss 0.2568 | val loss 0.3508 | acc 0.8747 | f1 0.6451 | prec 0.7365 | recall 0.5739 | roc auc 0.8415 | pr auc 0.7282 | elapsed 87.04s
train epoch 05/15 | batch 2001/2000 | loss 0.2070 | val loss 0.3313 |

[I 2024-07-30 03:21:55,060] Trial 13 finished with value: 15.346269574890714 and parameters: {'identity_weight': 12, 'decay': 941}. Best is trial 10 with value: 15.349425072967554.


train epoch 15/15 | batch 2001/2000 | loss 0.0769 | val loss 0.2827 | acc 0.9168 | f1 0.7906 | prec 0.7899 | recall 0.7912 | roc auc 0.9352 | pr auc 0.8818 | elapsed 87.74s
prc:  0.8818337970041976
roc:  0.9351865174747893
acc:  0.9168125
train epoch 00/15 | batch 2001/2000 | loss 1.1824 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 30.86s
train epoch 01/15 | batch 2001/2000 | loss 0.8480 | val loss 0.4759 | acc 0.8289 | f1 0.3429 | prec 0.7212 | recall 0.2249 | roc auc 0.6628 | pr auc 0.4674 | elapsed 88.84s
train epoch 02/15 | batch 2001/2000 | loss 0.5212 | val loss 0.4009 | acc 0.8435 | f1 0.5069 | prec 0.6763 | recall 0.4054 | roc auc 0.7752 | pr auc 0.6036 | elapsed 91.21s
train epoch 03/15 | batch 2001/2000 | loss 0.3663 | val loss 0.3779 | acc 0.8592 | f1 0.5993 | prec 0.6888 | recall 0.5304 | roc auc 0.8177 | pr auc 0.6800 | elapsed 90.77s
train epoch 04/15 | batch 2001/2000 | loss 0.2602 | val loss 0.3589 |

[I 2024-07-30 03:44:51,338] Trial 14 finished with value: 15.260471480923265 and parameters: {'identity_weight': 28, 'decay': 973}. Best is trial 10 with value: 15.349425072967554.


prc:  0.8755207520661719
roc:  0.9331898267102576
acc:  0.906125
train epoch 00/15 | batch 2001/2000 | loss 1.7054 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 30.61s
train epoch 01/15 | batch 2001/2000 | loss 1.1348 | val loss 0.4764 | acc 0.8251 | f1 0.3664 | prec 0.6519 | recall 0.2548 | roc auc 0.6686 | pr auc 0.4716 | elapsed 85.97s
train epoch 02/15 | batch 2001/2000 | loss 0.6516 | val loss 0.4046 | acc 0.8427 | f1 0.5219 | prec 0.6579 | recall 0.4324 | roc auc 0.7748 | pr auc 0.6044 | elapsed 89.09s
train epoch 03/15 | batch 2001/2000 | loss 0.4357 | val loss 0.3827 | acc 0.8550 | f1 0.6021 | prec 0.6610 | recall 0.5528 | roc auc 0.8180 | pr auc 0.6814 | elapsed 89.23s
train epoch 04/15 | batch 2001/2000 | loss 0.2743 | val loss 0.3617 | acc 0.8659 | f1 0.6468 | prec 0.6774 | recall 0.6189 | roc auc 0.8471 | pr auc 0.7342 | elapsed 89.46s
train epoch 05/15 | batch 2001/2000 | loss 0.2039 | val loss 0.3399 | 

[I 2024-07-30 04:07:40,955] Trial 15 finished with value: 15.187968423656331 and parameters: {'identity_weight': 64, 'decay': 929}. Best is trial 10 with value: 15.349425072967554.


train epoch 15/15 | batch 2001/2000 | loss 0.0817 | val loss 0.3085 | acc 0.9007 | f1 0.7607 | prec 0.7288 | recall 0.7956 | roc auc 0.9304 | pr auc 0.8705 | elapsed 87.64s
prc:  0.8705171129485866
roc:  0.9303516323617442
acc:  0.9006875
train epoch 00/15 | batch 2001/2000 | loss 1.0807 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 32.00s
train epoch 01/15 | batch 2001/2000 | loss 0.7805 | val loss 0.4779 | acc 0.8297 | f1 0.3310 | prec 0.7506 | recall 0.2123 | roc auc 0.6574 | pr auc 0.4626 | elapsed 86.95s
train epoch 02/15 | batch 2001/2000 | loss 0.4862 | val loss 0.4009 | acc 0.8436 | f1 0.4980 | prec 0.6860 | recall 0.3909 | roc auc 0.7736 | pr auc 0.6006 | elapsed 87.21s
train epoch 03/15 | batch 2001/2000 | loss 0.3473 | val loss 0.3759 | acc 0.8612 | f1 0.5972 | prec 0.7043 | recall 0.5184 | roc auc 0.8160 | pr auc 0.6778 | elapsed 88.99s
train epoch 04/15 | batch 2001/2000 | loss 0.2590 | val loss 0.3529 |

[I 2024-07-30 04:30:31,478] Trial 16 finished with value: 15.311373449887563 and parameters: {'identity_weight': 21, 'decay': 934}. Best is trial 10 with value: 15.349425072967554.


prc:  0.879308720696727
roc:  0.9343497904867154
acc:  0.9121875
train epoch 00/15 | batch 2001/2000 | loss 2.2284 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 32.70s
train epoch 01/15 | batch 2001/2000 | loss 1.4085 | val loss 0.4804 | acc 0.8203 | f1 0.3731 | prec 0.6058 | recall 0.2696 | roc auc 0.6677 | pr auc 0.4702 | elapsed 87.25s
train epoch 02/15 | batch 2001/2000 | loss 0.7763 | val loss 0.4097 | acc 0.8387 | f1 0.5206 | prec 0.6348 | recall 0.4413 | roc auc 0.7714 | pr auc 0.5998 | elapsed 87.78s
train epoch 03/15 | batch 2001/2000 | loss 0.5041 | val loss 0.3871 | acc 0.8514 | f1 0.5987 | prec 0.6449 | recall 0.5587 | roc auc 0.8160 | pr auc 0.6794 | elapsed 88.69s
train epoch 04/15 | batch 2001/2000 | loss 0.3021 | val loss 0.3678 | acc 0.8623 | f1 0.6442 | prec 0.6611 | recall 0.6280 | roc auc 0.8458 | pr auc 0.7328 | elapsed 87.60s
train epoch 05/15 | batch 2001/2000 | loss 0.2092 | val loss 0.3460 | 

[I 2024-07-30 04:53:11,381] Trial 17 finished with value: 15.147528354526933 and parameters: {'identity_weight': 100, 'decay': 902}. Best is trial 10 with value: 15.349425072967554.


train epoch 00/15 | batch 2001/2000 | loss 1.2551 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 32.62s
train epoch 01/15 | batch 2001/2000 | loss 0.8875 | val loss 0.4754 | acc 0.8284 | f1 0.3469 | prec 0.7091 | recall 0.2296 | roc auc 0.6647 | pr auc 0.4689 | elapsed 87.73s
train epoch 02/15 | batch 2001/2000 | loss 0.5382 | val loss 0.4011 | acc 0.8433 | f1 0.5103 | prec 0.6713 | recall 0.4117 | roc auc 0.7756 | pr auc 0.6045 | elapsed 88.46s
train epoch 03/15 | batch 2001/2000 | loss 0.3733 | val loss 0.3789 | acc 0.8582 | f1 0.5996 | prec 0.6822 | recall 0.5348 | roc auc 0.8180 | pr auc 0.6805 | elapsed 87.97s
train epoch 04/15 | batch 2001/2000 | loss 0.2593 | val loss 0.3590 | acc 0.8698 | f1 0.6496 | prec 0.6971 | recall 0.6082 | roc auc 0.8465 | pr auc 0.7321 | elapsed 89.16s
train epoch 05/15 | batch 2001/2000 | loss 0.1987 | val loss 0.3366 | acc 0.8787 | f1 0.6809 | prec 0.7122 | recall 0.6523 | roc auc 0.

[I 2024-07-30 05:15:52,129] Trial 18 finished with value: 15.248121535015038 and parameters: {'identity_weight': 33, 'decay': 960}. Best is trial 10 with value: 15.349425072967554.


train epoch 15/15 | batch 2001/2000 | loss 0.0816 | val loss 0.2963 | acc 0.9051 | f1 0.7677 | prec 0.7465 | recall 0.7902 | roc auc 0.9327 | pr auc 0.8747 | elapsed 88.77s
prc:  0.8746608009896468
roc:  0.932731420853095
acc:  0.905125
train epoch 00/15 | batch 2001/2000 | loss 1.0372 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 32.26s
train epoch 01/15 | batch 2001/2000 | loss 0.7564 | val loss 0.4769 | acc 0.8311 | f1 0.3258 | prec 0.7839 | recall 0.2057 | roc auc 0.6569 | pr auc 0.4618 | elapsed 86.65s
train epoch 02/15 | batch 2001/2000 | loss 0.4767 | val loss 0.4012 | acc 0.8437 | f1 0.4953 | prec 0.6893 | recall 0.3865 | roc auc 0.7731 | pr auc 0.5988 | elapsed 87.66s
train epoch 03/15 | batch 2001/2000 | loss 0.3440 | val loss 0.3763 | acc 0.8608 | f1 0.5942 | prec 0.7045 | recall 0.5137 | roc auc 0.8153 | pr auc 0.6763 | elapsed 88.46s
train epoch 04/15 | batch 2001/2000 | loss 0.2596 | val loss 0.3525 | a

[I 2024-07-30 05:38:27,910] Trial 19 finished with value: 15.320947296851827 and parameters: {'identity_weight': 18, 'decay': 947}. Best is trial 10 with value: 15.349425072967554.


prc:  0.8799804977470697
roc:  0.9347320532301884
acc:  0.91275
train epoch 00/15 | batch 2001/2000 | loss 0.9355 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 30.70s
train epoch 01/15 | batch 2001/2000 | loss 0.7017 | val loss 0.4811 | acc 0.8307 | f1 0.3039 | prec 0.8266 | recall 0.1861 | roc auc 0.6472 | pr auc 0.4522 | elapsed 84.56s
train epoch 02/15 | batch 2001/2000 | loss 0.4569 | val loss 0.4029 | acc 0.8438 | f1 0.4863 | prec 0.7000 | recall 0.3726 | roc auc 0.7698 | pr auc 0.5926 | elapsed 88.40s
train epoch 03/15 | batch 2001/2000 | loss 0.3358 | val loss 0.3771 | acc 0.8606 | f1 0.5874 | prec 0.7115 | recall 0.5002 | roc auc 0.8121 | pr auc 0.6711 | elapsed 86.88s
train epoch 04/15 | batch 2001/2000 | loss 0.2603 | val loss 0.3511 | acc 0.8747 | f1 0.6461 | prec 0.7349 | recall 0.5764 | roc auc 0.8420 | pr auc 0.7284 | elapsed 85.05s
train epoch 05/15 | batch 2001/2000 | loss 0.2094 | val loss 0.3323 | a

[I 2024-07-30 06:00:48,440] Trial 20 finished with value: 15.337816476578656 and parameters: {'identity_weight': 11, 'decay': 995}. Best is trial 10 with value: 15.349425072967554.


acc:  0.9146875
train epoch 00/15 | batch 2001/2000 | loss 0.9209 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 31.55s
train epoch 01/15 | batch 2001/2000 | loss 0.6875 | val loss 0.4828 | acc 0.8307 | f1 0.2954 | prec 0.8478 | recall 0.1789 | roc auc 0.6433 | pr auc 0.4480 | elapsed 84.96s
train epoch 02/15 | batch 2001/2000 | loss 0.4483 | val loss 0.4037 | acc 0.8436 | f1 0.4815 | prec 0.7034 | recall 0.3660 | roc auc 0.7683 | pr auc 0.5897 | elapsed 85.89s
train epoch 03/15 | batch 2001/2000 | loss 0.3289 | val loss 0.3779 | acc 0.8598 | f1 0.5812 | prec 0.7132 | recall 0.4904 | roc auc 0.8100 | pr auc 0.6681 | elapsed 86.95s
train epoch 04/15 | batch 2001/2000 | loss 0.2552 | val loss 0.3512 | acc 0.8752 | f1 0.6432 | prec 0.7437 | recall 0.5666 | roc auc 0.8395 | pr auc 0.7258 | elapsed 82.69s
train epoch 05/15 | batch 2001/2000 | loss 0.2075 | val loss 0.3310 | acc 0.8844 | f1 0.6807 | prec 0.7530 | recall 0.6

[I 2024-07-30 06:23:00,257] Trial 21 finished with value: 15.352123754165543 and parameters: {'identity_weight': 10, 'decay': 937}. Best is trial 21 with value: 15.352123754165543.


train epoch 00/15 | batch 2001/2000 | loss 1.1824 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 31.69s
train epoch 01/15 | batch 2001/2000 | loss 0.8390 | val loss 0.4761 | acc 0.8289 | f1 0.3409 | prec 0.7232 | recall 0.2230 | roc auc 0.6623 | pr auc 0.4669 | elapsed 85.43s
train epoch 02/15 | batch 2001/2000 | loss 0.5127 | val loss 0.4008 | acc 0.8436 | f1 0.5058 | prec 0.6778 | recall 0.4035 | roc auc 0.7749 | pr auc 0.6032 | elapsed 85.18s
train epoch 03/15 | batch 2001/2000 | loss 0.3600 | val loss 0.3772 | acc 0.8598 | f1 0.5993 | prec 0.6920 | recall 0.5285 | roc auc 0.8174 | pr auc 0.6798 | elapsed 86.39s
train epoch 04/15 | batch 2001/2000 | loss 0.2592 | val loss 0.3574 | acc 0.8703 | f1 0.6478 | prec 0.7025 | recall 0.6009 | roc auc 0.8462 | pr auc 0.7316 | elapsed 89.80s
train epoch 05/15 | batch 2001/2000 | loss 0.1962 | val loss 0.3356 | acc 0.8794 | f1 0.6809 | prec 0.7167 | recall 0.6485 | roc auc 0.

[I 2024-07-30 06:45:10,034] Trial 22 finished with value: 15.284018336526293 and parameters: {'identity_weight': 28, 'decay': 937}. Best is trial 21 with value: 15.352123754165543.


train epoch 00/15 | batch 2001/2000 | loss 1.0517 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 31.16s
train epoch 01/15 | batch 2001/2000 | loss 0.7617 | val loss 0.4767 | acc 0.8311 | f1 0.3272 | prec 0.7812 | recall 0.2069 | roc auc 0.6574 | pr auc 0.4623 | elapsed 86.15s
train epoch 02/15 | batch 2001/2000 | loss 0.4772 | val loss 0.4010 | acc 0.8438 | f1 0.4958 | prec 0.6893 | recall 0.3871 | roc auc 0.7732 | pr auc 0.5991 | elapsed 85.74s
train epoch 03/15 | batch 2001/2000 | loss 0.3432 | val loss 0.3762 | acc 0.8608 | f1 0.5941 | prec 0.7050 | recall 0.5134 | roc auc 0.8153 | pr auc 0.6765 | elapsed 86.03s
train epoch 04/15 | batch 2001/2000 | loss 0.2586 | val loss 0.3523 | acc 0.8738 | f1 0.6492 | prec 0.7240 | recall 0.5883 | roc auc 0.8448 | pr auc 0.7316 | elapsed 86.84s
train epoch 05/15 | batch 2001/2000 | loss 0.2008 | val loss 0.3367 | acc 0.8807 | f1 0.6820 | prec 0.7238 | recall 0.6447 | roc auc 0.

[I 2024-07-30 07:07:22,497] Trial 23 finished with value: 15.32388564916166 and parameters: {'identity_weight': 19, 'decay': 927}. Best is trial 21 with value: 15.352123754165543.


roc:  0.9346846188086139
acc:  0.913625
train epoch 00/15 | batch 2001/2000 | loss 0.9209 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 32.39s
train epoch 01/15 | batch 2001/2000 | loss 0.6891 | val loss 0.4826 | acc 0.8306 | f1 0.2961 | prec 0.8444 | recall 0.1795 | roc auc 0.6438 | pr auc 0.4485 | elapsed 86.86s
train epoch 02/15 | batch 2001/2000 | loss 0.4498 | val loss 0.4036 | acc 0.8436 | f1 0.4824 | prec 0.7028 | recall 0.3672 | roc auc 0.7685 | pr auc 0.5901 | elapsed 85.81s
train epoch 03/15 | batch 2001/2000 | loss 0.3304 | val loss 0.3778 | acc 0.8600 | f1 0.5826 | prec 0.7134 | recall 0.4923 | roc auc 0.8104 | pr auc 0.6686 | elapsed 85.23s
train epoch 04/15 | batch 2001/2000 | loss 0.2566 | val loss 0.3511 | acc 0.8752 | f1 0.6438 | prec 0.7427 | recall 0.5682 | roc auc 0.8400 | pr auc 0.7263 | elapsed 87.30s
train epoch 05/15 | batch 2001/2000 | loss 0.2085 | val loss 0.3311 | acc 0.8841 | f1 0.6809 | 

[I 2024-07-30 07:29:38,308] Trial 24 finished with value: 15.351652046764283 and parameters: {'identity_weight': 10, 'decay': 955}. Best is trial 21 with value: 15.352123754165543.


train epoch 15/15 | batch 2001/2000 | loss 0.0773 | val loss 0.2818 | acc 0.9177 | f1 0.7927 | prec 0.7923 | recall 0.7931 | roc auc 0.9353 | pr auc 0.8822 | elapsed 85.17s
prc:  0.8821873005575351
roc:  0.9353485901981551
acc:  0.9176875
train epoch 00/15 | batch 2001/2000 | loss 1.2986 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 30.41s
train epoch 01/15 | batch 2001/2000 | loss 0.9119 | val loss 0.4752 | acc 0.8279 | f1 0.3493 | prec 0.6998 | recall 0.2328 | roc auc 0.6655 | pr auc 0.4696 | elapsed 86.11s
train epoch 02/15 | batch 2001/2000 | loss 0.5493 | val loss 0.4013 | acc 0.8437 | f1 0.5135 | prec 0.6714 | recall 0.4157 | roc auc 0.7757 | pr auc 0.6049 | elapsed 87.35s
train epoch 03/15 | batch 2001/2000 | loss 0.3784 | val loss 0.3795 | acc 0.8581 | f1 0.6005 | prec 0.6801 | recall 0.5376 | roc auc 0.8182 | pr auc 0.6808 | elapsed 87.01s
train epoch 04/15 | batch 2001/2000 | loss 0.2595 | val loss 0.3593 |

[I 2024-07-30 07:51:51,597] Trial 25 finished with value: 15.237650512281368 and parameters: {'identity_weight': 36, 'decay': 956}. Best is trial 21 with value: 15.352123754165543.


acc:  0.904375
train epoch 00/15 | batch 2001/2000 | loss 1.1534 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 31.05s
train epoch 01/15 | batch 2001/2000 | loss 0.8307 | val loss 0.4763 | acc 0.8290 | f1 0.3404 | prec 0.7256 | recall 0.2224 | roc auc 0.6617 | pr auc 0.4664 | elapsed 84.63s
train epoch 02/15 | batch 2001/2000 | loss 0.5131 | val loss 0.4008 | acc 0.8436 | f1 0.5059 | prec 0.6781 | recall 0.4035 | roc auc 0.7749 | pr auc 0.6030 | elapsed 86.91s
train epoch 03/15 | batch 2001/2000 | loss 0.3624 | val loss 0.3775 | acc 0.8595 | f1 0.5990 | prec 0.6907 | recall 0.5288 | roc auc 0.8174 | pr auc 0.6796 | elapsed 88.08s
train epoch 04/15 | batch 2001/2000 | loss 0.2604 | val loss 0.3584 | acc 0.8702 | f1 0.6483 | prec 0.7015 | recall 0.6025 | roc auc 0.8462 | pr auc 0.7310 | elapsed 87.86s
train epoch 05/15 | batch 2001/2000 | loss 0.1978 | val loss 0.3356 | acc 0.8794 | f1 0.6811 | prec 0.7168 | recall 0.64

[I 2024-07-30 08:13:57,988] Trial 26 finished with value: 15.269738634107474 and parameters: {'identity_weight': 26, 'decay': 973}. Best is trial 21 with value: 15.352123754165543.


train epoch 15/15 | batch 2001/2000 | loss 0.0813 | val loss 0.2929 | acc 0.9074 | f1 0.7726 | prec 0.7532 | recall 0.7931 | roc auc 0.9335 | pr auc 0.8762 | elapsed 86.92s
prc:  0.8761626147345951
roc:  0.9334562477935873
acc:  0.907375
train epoch 00/15 | batch 2001/2000 | loss 1.0372 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 31.38s
train epoch 01/15 | batch 2001/2000 | loss 0.7598 | val loss 0.4767 | acc 0.8313 | f1 0.3270 | prec 0.7838 | recall 0.2066 | roc auc 0.6572 | pr auc 0.4622 | elapsed 85.61s
train epoch 02/15 | batch 2001/2000 | loss 0.4798 | val loss 0.4011 | acc 0.8436 | f1 0.4955 | prec 0.6881 | recall 0.3871 | roc auc 0.7733 | pr auc 0.5993 | elapsed 87.01s
train epoch 03/15 | batch 2001/2000 | loss 0.3466 | val loss 0.3764 | acc 0.8610 | f1 0.5958 | prec 0.7043 | recall 0.5162 | roc auc 0.8156 | pr auc 0.6766 | elapsed 86.05s
train epoch 04/15 | batch 2001/2000 | loss 0.2609 | val loss 0.3531 | 

[I 2024-07-30 08:36:20,777] Trial 27 finished with value: 15.312275090347669 and parameters: {'identity_weight': 18, 'decay': 967}. Best is trial 21 with value: 15.352123754165543.


train epoch 00/15 | batch 2001/2000 | loss 1.7345 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 32.43s
train epoch 01/15 | batch 2001/2000 | loss 1.1449 | val loss 0.4764 | acc 0.8251 | f1 0.3666 | prec 0.6511 | recall 0.2551 | roc auc 0.6687 | pr auc 0.4716 | elapsed 86.33s
train epoch 02/15 | batch 2001/2000 | loss 0.6535 | val loss 0.4047 | acc 0.8427 | f1 0.5220 | prec 0.6577 | recall 0.4328 | roc auc 0.7747 | pr auc 0.6043 | elapsed 89.27s
train epoch 03/15 | batch 2001/2000 | loss 0.4359 | val loss 0.3827 | acc 0.8551 | f1 0.6023 | prec 0.6615 | recall 0.5528 | roc auc 0.8179 | pr auc 0.6814 | elapsed 90.22s
train epoch 04/15 | batch 2001/2000 | loss 0.2750 | val loss 0.3618 | acc 0.8659 | f1 0.6467 | prec 0.6775 | recall 0.6186 | roc auc 0.8471 | pr auc 0.7341 | elapsed 91.07s
train epoch 05/15 | batch 2001/2000 | loss 0.2033 | val loss 0.3397 | acc 0.8745 | f1 0.6750 | prec 0.6943 | recall 0.6567 | roc auc 0.

[I 2024-07-30 08:59:31,215] Trial 28 finished with value: 15.19504665491181 and parameters: {'identity_weight': 66, 'decay': 918}. Best is trial 21 with value: 15.352123754165543.


train epoch 00/15 | batch 2001/2000 | loss 1.3422 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 30.71s
train epoch 01/15 | batch 2001/2000 | loss 0.9394 | val loss 0.4753 | acc 0.8275 | f1 0.3506 | prec 0.6930 | recall 0.2346 | roc auc 0.6660 | pr auc 0.4699 | elapsed 95.81s
train epoch 02/15 | batch 2001/2000 | loss 0.5634 | val loss 0.4016 | acc 0.8436 | f1 0.5147 | prec 0.6699 | recall 0.4180 | roc auc 0.7758 | pr auc 0.6052 | elapsed 100.23s
train epoch 03/15 | batch 2001/2000 | loss 0.3854 | val loss 0.3803 | acc 0.8581 | f1 0.6020 | prec 0.6789 | recall 0.5408 | roc auc 0.8183 | pr auc 0.6809 | elapsed 100.96s
train epoch 04/15 | batch 2001/2000 | loss 0.2601 | val loss 0.3595 | acc 0.8691 | f1 0.6498 | prec 0.6927 | recall 0.6120 | roc auc 0.8468 | pr auc 0.7331 | elapsed 101.42s
train epoch 05/15 | batch 2001/2000 | loss 0.2005 | val loss 0.3375 | acc 0.8774 | f1 0.6791 | prec 0.7067 | recall 0.6535 | roc auc

[I 2024-07-30 09:25:14,289] Trial 29 finished with value: 15.222964792273162 and parameters: {'identity_weight': 39, 'decay': 961}. Best is trial 21 with value: 15.352123754165543.


train epoch 15/15 | batch 2001/2000 | loss 0.0828 | val loss 0.3009 | acc 0.9027 | f1 0.7632 | prec 0.7379 | recall 0.7902 | roc auc 0.9319 | pr auc 0.8729 | elapsed 102.01s
prc:  0.8728954807583746
roc:  0.9318870807815689
acc:  0.9026875
train epoch 00/15 | batch 2001/2000 | loss 1.2405 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 36.62s
train epoch 01/15 | batch 2001/2000 | loss 0.8752 | val loss 0.4755 | acc 0.8284 | f1 0.3450 | prec 0.7116 | recall 0.2277 | roc auc 0.6642 | pr auc 0.4685 | elapsed 102.10s
train epoch 02/15 | batch 2001/2000 | loss 0.5307 | val loss 0.4010 | acc 0.8436 | f1 0.5094 | prec 0.6748 | recall 0.4091 | roc auc 0.7754 | pr auc 0.6042 | elapsed 103.66s
train epoch 03/15 | batch 2001/2000 | loss 0.3691 | val loss 0.3783 | acc 0.8586 | f1 0.5994 | prec 0.6847 | recall 0.5329 | roc auc 0.8179 | pr auc 0.6804 | elapsed 104.32s
train epoch 04/15 | batch 2001/2000 | loss 0.2590 | val loss 0.35

[I 2024-07-30 09:52:48,263] Trial 30 finished with value: 15.262068062157768 and parameters: {'identity_weight': 32, 'decay': 947}. Best is trial 21 with value: 15.352123754165543.


prc:  0.8756276974530562
roc:  0.9330901812712008
acc:  0.90725
train epoch 00/15 | batch 2001/2000 | loss 0.9355 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 31.99s
train epoch 01/15 | batch 2001/2000 | loss 0.6966 | val loss 0.4817 | acc 0.8306 | f1 0.3012 | prec 0.8307 | recall 0.1839 | roc auc 0.6459 | pr auc 0.4508 | elapsed 86.52s
train epoch 02/15 | batch 2001/2000 | loss 0.4521 | val loss 0.4032 | acc 0.8438 | f1 0.4851 | prec 0.7014 | recall 0.3707 | roc auc 0.7692 | pr auc 0.5914 | elapsed 89.83s
train epoch 03/15 | batch 2001/2000 | loss 0.3311 | val loss 0.3774 | acc 0.8607 | f1 0.5859 | prec 0.7142 | recall 0.4967 | roc auc 0.8111 | pr auc 0.6698 | elapsed 87.49s
train epoch 04/15 | batch 2001/2000 | loss 0.2564 | val loss 0.3509 | acc 0.8748 | f1 0.6440 | prec 0.7390 | recall 0.5707 | roc auc 0.8407 | pr auc 0.7272 | elapsed 85.75s
train epoch 05/15 | batch 2001/2000 | loss 0.2076 | val loss 0.3311 | a

[I 2024-07-30 10:14:57,038] Trial 31 finished with value: 15.349218842539791 and parameters: {'identity_weight': 11, 'decay': 944}. Best is trial 21 with value: 15.352123754165543.


acc:  0.91775
train epoch 00/15 | batch 2001/2000 | loss 1.0226 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 29.98s
train epoch 01/15 | batch 2001/2000 | loss 0.7489 | val loss 0.4773 | acc 0.8313 | f1 0.3236 | prec 0.7907 | recall 0.2035 | roc auc 0.6559 | pr auc 0.4609 | elapsed 87.44s
train epoch 02/15 | batch 2001/2000 | loss 0.4740 | val loss 0.4013 | acc 0.8438 | f1 0.4953 | prec 0.6903 | recall 0.3861 | roc auc 0.7727 | pr auc 0.5982 | elapsed 83.29s
train epoch 03/15 | batch 2001/2000 | loss 0.3430 | val loss 0.3764 | acc 0.8607 | f1 0.5932 | prec 0.7053 | recall 0.5118 | roc auc 0.8150 | pr auc 0.6758 | elapsed 86.40s
train epoch 04/15 | batch 2001/2000 | loss 0.2599 | val loss 0.3523 | acc 0.8734 | f1 0.6479 | prec 0.7232 | recall 0.5868 | roc auc 0.8446 | pr auc 0.7312 | elapsed 87.70s
train epoch 05/15 | batch 2001/2000 | loss 0.2023 | val loss 0.3367 | acc 0.8812 | f1 0.6831 | prec 0.7256 | recall 0.645

[I 2024-07-30 10:36:52,127] Trial 32 finished with value: 15.322573436389863 and parameters: {'identity_weight': 17, 'decay': 954}. Best is trial 21 with value: 15.352123754165543.


acc:  0.9133125
train epoch 00/15 | batch 2001/2000 | loss 0.9355 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 32.49s
train epoch 01/15 | batch 2001/2000 | loss 0.6957 | val loss 0.4818 | acc 0.8306 | f1 0.3005 | prec 0.8326 | recall 0.1833 | roc auc 0.6456 | pr auc 0.4506 | elapsed 83.79s
train epoch 02/15 | batch 2001/2000 | loss 0.4512 | val loss 0.4033 | acc 0.8437 | f1 0.4842 | prec 0.7013 | recall 0.3698 | roc auc 0.7690 | pr auc 0.5912 | elapsed 89.75s
train epoch 03/15 | batch 2001/2000 | loss 0.3303 | val loss 0.3775 | acc 0.8605 | f1 0.5847 | prec 0.7144 | recall 0.4948 | roc auc 0.8109 | pr auc 0.6695 | elapsed 91.08s
train epoch 04/15 | batch 2001/2000 | loss 0.2557 | val loss 0.3509 | acc 0.8750 | f1 0.6439 | prec 0.7407 | recall 0.5694 | roc auc 0.8405 | pr auc 0.7270 | elapsed 90.75s
train epoch 05/15 | batch 2001/2000 | loss 0.2072 | val loss 0.3310 | acc 0.8838 | f1 0.6810 | prec 0.7481 | recall 0.6

[I 2024-07-30 10:59:54,895] Trial 33 finished with value: 15.349443440644574 and parameters: {'identity_weight': 11, 'decay': 935}. Best is trial 21 with value: 15.352123754165543.


roc:  0.9351729489954106
acc:  0.9176875
train epoch 00/15 | batch 2001/2000 | loss 1.1388 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 33.47s
train epoch 01/15 | batch 2001/2000 | loss 0.8130 | val loss 0.4767 | acc 0.8291 | f1 0.3364 | prec 0.7333 | recall 0.2183 | roc auc 0.6604 | pr auc 0.4653 | elapsed 87.95s
train epoch 02/15 | batch 2001/2000 | loss 0.5004 | val loss 0.4007 | acc 0.8439 | f1 0.5040 | prec 0.6819 | recall 0.3997 | roc auc 0.7745 | pr auc 0.6022 | elapsed 93.05s
train epoch 03/15 | batch 2001/2000 | loss 0.3540 | val loss 0.3765 | acc 0.8599 | f1 0.5969 | prec 0.6959 | recall 0.5225 | roc auc 0.8169 | pr auc 0.6791 | elapsed 92.66s
train epoch 04/15 | batch 2001/2000 | loss 0.2591 | val loss 0.3552 | acc 0.8728 | f1 0.6517 | prec 0.7132 | recall 0.6000 | roc auc 0.8460 | pr auc 0.7321 | elapsed 92.56s
train epoch 05/15 | batch 2001/2000 | loss 0.1963 | val loss 0.3352 | acc 0.8796 | f1 0.6810 |

[I 2024-07-30 11:23:44,233] Trial 34 finished with value: 15.296760044043994 and parameters: {'identity_weight': 25, 'decay': 932}. Best is trial 21 with value: 15.352123754165543.


acc:  0.910375
train epoch 00/15 | batch 2001/2000 | loss 0.9209 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 32.84s
train epoch 01/15 | batch 2001/2000 | loss 0.6861 | val loss 0.4830 | acc 0.8306 | f1 0.2942 | prec 0.8483 | recall 0.1780 | roc auc 0.6428 | pr auc 0.4475 | elapsed 90.14s
train epoch 02/15 | batch 2001/2000 | loss 0.4469 | val loss 0.4039 | acc 0.8434 | f1 0.4799 | prec 0.7036 | recall 0.3641 | roc auc 0.7680 | pr auc 0.5892 | elapsed 94.16s
train epoch 03/15 | batch 2001/2000 | loss 0.3275 | val loss 0.3781 | acc 0.8597 | f1 0.5808 | prec 0.7133 | recall 0.4898 | roc auc 0.8096 | pr auc 0.6676 | elapsed 93.20s
train epoch 04/15 | batch 2001/2000 | loss 0.2540 | val loss 0.3514 | acc 0.8752 | f1 0.6426 | prec 0.7447 | recall 0.5650 | roc auc 0.8390 | pr auc 0.7252 | elapsed 91.97s
train epoch 05/15 | batch 2001/2000 | loss 0.2066 | val loss 0.3313 | acc 0.8846 | f1 0.6806 | prec 0.7551 | recall 0.61

[I 2024-07-30 11:46:29,826] Trial 35 finished with value: 15.350145086814234 and parameters: {'identity_weight': 10, 'decay': 921}. Best is trial 21 with value: 15.352123754165543.


prc:  0.8821588278208072
roc:  0.9349990514343601
acc:  0.9185625
train epoch 00/15 | batch 2001/2000 | loss 1.0081 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 30.77s
train epoch 01/15 | batch 2001/2000 | loss 0.7340 | val loss 0.4782 | acc 0.8311 | f1 0.3183 | prec 0.7987 | recall 0.1987 | roc auc 0.6537 | pr auc 0.4588 | elapsed 86.28s
train epoch 02/15 | batch 2001/2000 | loss 0.4645 | val loss 0.4017 | acc 0.8438 | f1 0.4920 | prec 0.6938 | recall 0.3811 | roc auc 0.7718 | pr auc 0.5965 | elapsed 84.75s
train epoch 03/15 | batch 2001/2000 | loss 0.3361 | val loss 0.3763 | acc 0.8602 | f1 0.5890 | prec 0.7073 | recall 0.5046 | roc auc 0.8138 | pr auc 0.6742 | elapsed 85.07s
train epoch 04/15 | batch 2001/2000 | loss 0.2564 | val loss 0.3509 | acc 0.8742 | f1 0.6473 | prec 0.7299 | recall 0.5814 | roc auc 0.8433 | pr auc 0.7304 | elapsed 86.85s
train epoch 05/15 | batch 2001/2000 | loss 0.2038 | val loss 0.3326 |

[I 2024-07-30 12:08:50,156] Trial 36 finished with value: 15.338560831238821 and parameters: {'identity_weight': 16, 'decay': 910}. Best is trial 21 with value: 15.352123754165543.


train epoch 00/15 | batch 2001/2000 | loss 1.1098 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 30.65s
train epoch 01/15 | batch 2001/2000 | loss 0.7943 | val loss 0.4774 | acc 0.8294 | f1 0.3338 | prec 0.7411 | recall 0.2154 | roc auc 0.6588 | pr auc 0.4639 | elapsed 84.36s
train epoch 02/15 | batch 2001/2000 | loss 0.4909 | val loss 0.4008 | acc 0.8438 | f1 0.5008 | prec 0.6841 | recall 0.3950 | roc auc 0.7739 | pr auc 0.6012 | elapsed 85.87s
train epoch 03/15 | batch 2001/2000 | loss 0.3489 | val loss 0.3761 | acc 0.8613 | f1 0.5988 | prec 0.7029 | recall 0.5216 | roc auc 0.8163 | pr auc 0.6783 | elapsed 96.50s
train epoch 04/15 | batch 2001/2000 | loss 0.2584 | val loss 0.3536 | acc 0.8731 | f1 0.6499 | prec 0.7183 | recall 0.5934 | roc auc 0.8455 | pr auc 0.7322 | elapsed 99.11s
train epoch 05/15 | batch 2001/2000 | loss 0.1971 | val loss 0.3354 | acc 0.8803 | f1 0.6822 | prec 0.7211 | recall 0.6472 | roc auc 0.

[I 2024-07-30 12:34:34,999] Trial 37 finished with value: 15.307544241035316 and parameters: {'identity_weight': 23, 'decay': 921}. Best is trial 21 with value: 15.352123754165543.


prc:  0.8790478592580189
roc:  0.9341880247425212
acc:  0.9119375
train epoch 00/15 | batch 2001/2000 | loss 1.3567 | val loss 0.7750 | acc 0.1984 | f1 0.3312 | prec 0.1984 | recall 1.0000 | roc auc 0.5216 | pr auc 0.2296 | elapsed 40.56s
train epoch 01/15 | batch 2001/2000 | loss 0.9301 | val loss 0.4753 | acc 0.8277 | f1 0.3499 | prec 0.6961 | recall 0.2337 | roc auc 0.6659 | pr auc 0.4699 | elapsed 108.09s
train epoch 02/15 | batch 2001/2000 | loss 0.5508 | val loss 0.4013 | acc 0.8436 | f1 0.5131 | prec 0.6709 | recall 0.4154 | roc auc 0.7757 | pr auc 0.6050 | elapsed 109.45s
train epoch 03/15 | batch 2001/2000 | loss 0.3760 | val loss 0.3791 | acc 0.8580 | f1 0.6000 | prec 0.6802 | recall 0.5367 | roc auc 0.8181 | pr auc 0.6811 | elapsed 104.97s
train epoch 04/15 | batch 0536/2000 | loss 0.2863 | elapsed 27.40s

[W 2024-07-30 12:41:06,460] Trial 38 failed with parameters: {'identity_weight': 40, 'decay': 911} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/home/janek/miniconda3/envs/reasoner/lib/python3.9/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
  File "/tmp/ipykernel_4499/4089852266.py", line 16, in objective
    y, Y = train_mod(data_tr, data_vl, trained_reasoner, encoders, epoch_count=15,
  File "/home/janek/reasonable-embeddings/src/reasoner_mod.py", line 317, in train_mod
    loss, yb, Yb = eval_batch_mod(reasoner, encoders, X_tr, y_tr, idx_tr, idxs, backward=epoch_idx > 0,
  File "/home/janek/reasonable-embeddings/src/reasoner_mod.py", line 281, in eval_batch_mod
    loss.backward()
  File "/home/janek/miniconda3/envs/reasoner/lib/python3.9/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
 

KeyboardInterrupt: 

In [ ]:
## --- TESTING
trained_test_encoders = {}
T.manual_seed(seed)
test_logger = TrainingLogger(validate=True, metrics=batch_stats)

for reasoner_name, reasoner in [('trained reasoner', trained_reasoner)]:
    print(reasoner_name)
    T.manual_seed(seed)
    trained_test_encoders[reasoner_name] = test_encoders = [EmbeddingLayer.from_onto(onto, emb_size=emb_size) for onto in test_onto]
    train_mod(data_te_tr, data_te_vl, reasoner, test_encoders, epoch_count=test_epoch_count, batch_size=batch_size, run_name=reasoner_name, freeze_reasoner=True, logger=test_logger)

trained reasoner
train epoch 00/10 | batch 849/848 | loss 0.7694 | val loss 0.7728 | acc 0.2077 | f1 0.3440 | prec 0.2077 | recall 1.0000 | roc auc 0.4990 | pr auc 0.2375 | elapsed 7.20s
train epoch 01/10 | batch 849/848 | loss 0.7689 | val loss 0.7724 | acc 0.2077 | f1 0.3440 | prec 0.2077 | recall 1.0000 | roc auc 0.5104 | pr auc 0.2452 | elapsed 12.84s
train epoch 02/10 | batch 849/848 | loss 0.7677 | val loss 0.7720 | acc 0.2077 | f1 0.3440 | prec 0.2077 | recall 1.0000 | roc auc 0.5223 | pr auc 0.2537 | elapsed 12.80s
train epoch 03/10 | batch 849/848 | loss 0.7664 | val loss 0.7715 | acc 0.2077 | f1 0.3440 | prec 0.2077 | recall 1.0000 | roc auc 0.5342 | pr auc 0.2620 | elapsed 12.35s
train epoch 04/10 | batch 849/848 | loss 0.7651 | val loss 0.7711 | acc 0.2077 | f1 0.3440 | prec 0.2077 | recall 1.0000 | roc auc 0.5454 | pr auc 0.2704 | elapsed 12.64s
train epoch 05/10 | batch 849/848 | loss 0.7638 | val loss 0.7706 | acc 0.2077 | f1 0.3440 | prec 0.2077 | recall 1.0000 | roc au

In [ ]:
with T.no_grad():
    # idx_te, X_te, y_te = data_te
    _, _, Y_te_good = eval_batch(trained_reasoner, trained_test_encoders['trained reasoner'], X_te_te, y_te_te, idx_te_te)
    # _, _, Y_te_rand = eval_batch(random_reasoner, trained_test_encoders['random reasoner'], X_te, y_te, idx_te)

In [ ]:
base = 'local/out/exp/' + ts
mkdirp(base)
print(base)

T.save(trained_reasoner.state_dict(), base+'/reasoner.pt')
df_tr = pd.DataFrame(train_logger.history_tr)
df_vl = pd.DataFrame(train_logger.history_vl)
df_tr.to_csv(base+'/train.csv', index=False)
df_vl.to_csv(base+'/valid.csv', index=False)
plot_train_history(df_tr, df_vl, save=base+'/train.png')

test_history_by_onto = pd.DataFrame(test_logger.history_vl_by_onto)
test_history = pd.DataFrame(test_logger.history_vl)
test_results = pd.DataFrame(dict(idx_te=idx_te_te, y_te=y_te_te, Y_te_good=Y_te_good))
test_history.to_csv(base+'/test.csv', index=False)
test_history_by_onto.to_csv(base+'/test-grouped.csv', index=False)
test_results.to_csv(base+'/test-results.csv', index=False)
plot_test_history(test_history, test_history_by_onto)
print(report(test_onto, y_te_te, np.array(Y_te_good), idx_te_te))
# print(report(test_onto, y_te, np.array(Y_te_rand), idx_te))

local/out/exp/20240716T183807


NameError: name 'train_logger' is not defined

In [ ]:
import random

In [ ]:
losses = []
for _ in range(20):
    encoder = trained_test_encoders['trained reasoner'][int(np.round(random.random() * (len(trained_test_encoders['trained reasoner'] ) - 1) , 0))]
    input = encoder.concepts[ int(np.round( random.random() * encoder.n_concepts , 0) - 1) ]
    losses.append( F.l1_loss(input, trained_reasoner.and_nn(im(input, input))).item() )


print(input)
print(trained_reasoner.and_nn(im( input, input)))
print(np.mean(losses))

tensor([-0.0853,  0.0049,  0.0044,  0.1040, -0.2791, -0.0971, -0.0545, -0.2373,
         0.0291, -0.1781], grad_fn=<SelectBackward0>)
tensor([ 0.0283, -0.1301,  0.1543, -0.1816,  0.1470, -0.1504, -0.1508, -0.1428,
         0.1558,  0.1439], grad_fn=<AddBackward0>)
0.14532663188874723


In [ ]:
losses = []
for _ in range(20):
    encoder = trained_test_encoders['trained reasoner'][int(np.round(random.random() * (len(trained_test_encoders['trained reasoner'] ) - 1) , 0))]
    input = encoder.concepts[ int(np.round( random.random() * encoder.n_concepts , 0) - 1) ]
    losses.append(F.l1_loss(trained_reasoner.and_nn(im(trained_reasoner.bot_concept[0], input)), trained_reasoner.bot_concept[0]).item())
print(trained_reasoner.bot_concept[0])
print(trained_reasoner.and_nn(im(trained_reasoner.bot_concept[0], input)))
print(np.mean(losses))

tensor([ 0.8487,  0.3154, -0.0030, -0.4652,  0.9116, -0.0422,  0.2849,  0.1790,
        -0.4642, -0.3235], grad_fn=<SelectBackward0>)
tensor([ 0.5006,  0.4196, -0.2333, -0.1082,  0.1215,  0.4181,  0.3491,  0.4251,
        -0.4716, -0.1767], grad_fn=<AddBackward0>)
0.27251186221838


In [ ]:
losses = []
for _ in range(20):
    encoder = trained_test_encoders['trained reasoner'][int(np.round(random.random() * (len(trained_test_encoders['trained reasoner'] ) - 1) , 0))]
    input = encoder.concepts[ int(np.round( random.random() * encoder.n_concepts , 0) - 1) ]
    losses.append(F.l1_loss(trained_reasoner.and_nn(im(trained_reasoner.top_concept[0], input)), input).item())

print(input)
print(trained_reasoner.and_nn(im(trained_reasoner.top_concept[0], input)))
print(np.mean(losses))

tensor([ 0.0393, -0.1274, -0.2614, -0.1177, -0.0585, -0.0664,  0.1144, -0.2802,
         0.1001,  0.0221], grad_fn=<SelectBackward0>)
tensor([-0.2182, -0.3193,  0.2273, -0.1661,  0.1478, -0.1756, -0.1602, -0.2823,
         0.2452,  0.2916], grad_fn=<AddBackward0>)
0.1793355718255043


In [ ]:
losses = []
for _ in range(20):

    encoder = trained_test_encoders['trained reasoner'][int(np.round(random.random() * (len(trained_test_encoders['trained reasoner'] ) - 1) , 0))]
    input = encoder.concepts[ int(np.round( random.random() * encoder.n_concepts , 0) - 1) ]
    output = trained_reasoner.and_nn(im(trained_reasoner.not_nn(input), input))
    losses.append(F.l1_loss(trained_reasoner.bot_concept[0], output).item())

print(trained_reasoner.bot_concept[0])
print(output)
print(np.mean(losses))

tensor([ 0.8487,  0.3154, -0.0030, -0.4652,  0.9116, -0.0422,  0.2849,  0.1790,
        -0.4642, -0.3235], grad_fn=<SelectBackward0>)


tensor([ 0.0291, -0.0860,  0.1372, -0.2300,  0.1739, -0.1169, -0.1536, -0.1260,
         0.1137,  0.0972], grad_fn=<AddBackward0>)
0.36536308377981186


In [ ]:
print(trained_reasoner.bot_concept[0])
output = trained_reasoner.not_nn(trained_reasoner.top_concept[0])
print(output)
print(F.l1_loss(trained_reasoner.bot_concept[0], output))

tensor([ 0.8487,  0.3154, -0.0030, -0.4652,  0.9116, -0.0422,  0.2849,  0.1790,
        -0.4642, -0.3235], grad_fn=<SelectBackward0>)
tensor([ 0.8487,  0.3152, -0.0028, -0.4649,  0.9116, -0.0422,  0.2849,  0.1790,
        -0.4640, -0.3235], grad_fn=<SqueezeBackward3>)
tensor(9.1464e-05, grad_fn=<L1LossBackward0>)


In [ ]:
print(trained_reasoner.top_concept[0])
output = trained_reasoner.not_nn(trained_reasoner.bot_concept[0])
print(output)
print(F.l1_loss(trained_reasoner.top_concept[0], output))

tensor([ 0.0286, -0.2194,  0.0205,  0.4425,  0.1463,  0.3542,  1.5009,  0.0721,
        -0.2669,  0.2835], grad_fn=<SelectBackward0>)
tensor([ 0.0288, -0.2195,  0.0202,  0.4425,  0.1462,  0.3544,  1.5013,  0.0722,
        -0.2671,  0.2835], grad_fn=<SqueezeBackward3>)
tensor(0.0001, grad_fn=<L1LossBackward0>)


In [ ]:
losses = []
for _ in range(20):
    encoder = trained_test_encoders['trained reasoner'][int(np.round(random.random() * (len(trained_test_encoders['trained reasoner'] ) - 1) , 0))]
    input1 = encoder.concepts[int(np.round(random. random() * encoder.n_concepts, 0) - 1)]

    input2 = encoder.concepts[int(np.round(random. random() * encoder.n_concepts, 0) - 1)]

    input3 = encoder.concepts[int(np.round(random. random() * encoder.n_concepts, 0) - 1)]

    losses.append(F.l1_loss(trained_reasoner.and_nn(im(input1, trained_reasoner.and_nn(im(input2, input3)))), trained_reasoner.and_nn(im(trained_reasoner.and_nn(im(input1, input2)), input3))).item())

print(trained_reasoner.and_nn(im(input1, trained_reasoner.and_nn(im(input2, input3)))))
print(trained_reasoner.and_nn(im(trained_reasoner.and_nn(im(input1, input2)), input3)))
print(np.mean(losses))

tensor([ 0.1326, -0.0631,  0.0128, -0.1697,  0.1839,  0.0128, -0.0778, -0.0954,
        -0.0058,  0.0982], grad_fn=<AddBackward0>)
tensor([ 0.0459,  0.0285,  0.0899, -0.2081,  0.1915, -0.0053, -0.0852, -0.0492,
        -0.0394,  0.0515], grad_fn=<AddBackward0>)
0.03770795250311494


In [ ]:
losses = []
for _ in range(20):
    encoder = trained_test_encoders['trained reasoner'][int(np.round(random.random() * (len(trained_test_encoders['trained reasoner'] ) - 1) , 0))]
    input1 = encoder.concepts[int(np.round(random. random() * encoder.n_concepts, 0) - 1)]
    input2 = encoder.concepts[int(np.round(random. random() * encoder.n_concepts, 0) - 1)]

    losses.append( F.l1_loss(trained_reasoner.and_nn(im(input1, input2)), trained_reasoner.and_nn(im(input2, input1))).item())

print(trained_reasoner.and_nn(im(input1, input2)))
print(trained_reasoner.and_nn(im(input2, input1)))

print(np.mean(losses))

tensor([ 0.0574,  0.0155,  0.0813, -0.1991,  0.1782,  0.0296, -0.0436,  0.0211,
        -0.0320,  0.0349], grad_fn=<AddBackward0>)
tensor([ 0.1004, -0.0202,  0.0521, -0.2140,  0.1707, -0.0263, -0.0697,  0.0596,
        -0.1071,  0.0224], grad_fn=<AddBackward0>)
0.029833172308281065


In [ ]:
losses = []
for _ in range(20):
    encoder = trained_test_encoders['trained reasoner'][int(np.round(random.random() * (len(trained_test_encoders['trained reasoner'] ) - 1) , 0))]
    input1 = encoder.concepts[int(np.round(random. random() * encoder.n_concepts, 0) - 1)]
    losses.append(F.l1_loss(input1, trained_reasoner.and_nn(im(input1, trained_reasoner.top_concept[0]))).item())

print(input1)
print(trained_reasoner.and_nn(im(input1, trained_reasoner.top_concept[0])))

print(np.mean(losses))

tensor([ 0.1733,  0.2138, -0.0319, -0.2493,  0.1992,  0.0884,  0.0452,  0.0611,
        -0.2770,  0.0685], grad_fn=<SelectBackward0>)
tensor([ 0.0836,  0.1108,  0.0115, -0.2417,  0.0640,  0.0104,  0.0819,  0.1758,
        -0.1955, -0.0690], grad_fn=<AddBackward0>)
0.1997889805585146


In [ ]:
losses = []
for _ in range(20):
    encoder = trained_test_encoders['trained reasoner'][int(np.round(random.random() * (len(trained_test_encoders['trained reasoner'] ) - 1) , 0))]
    input1 = encoder.concepts[int(np.round(random. random() * encoder.n_concepts, 0) - 1)]
    losses.append( T.sigmoid(trained_reasoner.sub_nn(im(input1, trained_reasoner.top_concept[0]))).item())
print(np.mean(losses))

0.9999014347791672


In [ ]:
losses = []
for _ in range(20):
    encoder = trained_test_encoders['trained reasoner'][int(np.round(random.random() * (len(trained_test_encoders['trained reasoner'] ) - 1) , 0))]
    input1 = encoder.concepts[int(np.round(random. random() * encoder.n_concepts, 0) - 1)]
    losses.append(T.sigmoid(trained_reasoner.sub_nn(im(trained_reasoner.bot_concept[0], trained_reasoner.bot_concept[0]))).item())
print(np.mean(losses))

1.0
