In [12]:
import torch

# Ustawiamy ziarno dla powtarzalności wyników
torch.manual_seed(42)

# Generujemy nietrywialną macierz inwolucyjną 6x6
def generate_involutory_matrix():
    # Tworzymy losową macierz ortogonalną
    A = torch.randn(6, 6)
    Q, _ = torch.linalg.qr(A)
    
    # Tworzymy macierz diagonalną z 1 i -1
    D = torch.diag(torch.tensor([1., -1., 1., -1., 1., -1.]))
    
    # Tworzymy macierz inwolucyjną
    M = Q @ D @ Q.T
    
    return M

# Generujemy macierz inwolucyjną
M = generate_involutory_matrix()

print("Macierz inwolucyjna M:")
print(M)

# Sprawdzamy, czy M * M = I
I = torch.eye(6)
MM = M @ M
print("\nM * M:")
print(MM)
print("\nRóżnica między M * M a macierzą jednostkową:")
print(torch.abs(MM - I).max().item())

# Generujemy losową macierz 6x6
R = torch.randn(6, 6)
print("\nLosowa macierz R:")
print(R)

# Mnożymy R przez M dwukrotnie
RM = R @ M
RMM = RM @ M

print("\nR * M:")
print(RM)
print("\nR * M * M (powinno być równe R):")
print(RMM)
print("\nRóżnica między R a R * M * M:")
print(torch.abs(R - RMM).max().item())

Macierz inwolucyjna M:
tensor([[ 0.4406, -0.0910, -0.2629, -0.3710, -0.5047, -0.5798],
        [-0.0910, -0.9789, -0.0882,  0.0116,  0.1588, -0.0212],
        [-0.2629, -0.0882,  0.6110,  0.4634, -0.4393, -0.3769],
        [-0.3710,  0.0116,  0.4634, -0.7783,  0.1561, -0.1317],
        [-0.5047,  0.1588, -0.4393,  0.1561,  0.3519, -0.6155],
        [-0.5798, -0.0212, -0.3769, -0.1317, -0.6155,  0.3538]])

M * M:
tensor([[ 1.0000e+00, -1.1828e-07, -8.9407e-08, -1.7881e-07, -2.9802e-08,
          1.4901e-08],
        [-1.1828e-07,  1.0000e+00,  0.0000e+00, -2.1211e-07, -3.6322e-08,
         -1.2247e-07],
        [-8.9407e-08,  0.0000e+00,  1.0000e+00, -7.4506e-09,  1.0431e-07,
         -1.6391e-07],
        [-1.7881e-07, -2.1211e-07, -7.4506e-09,  1.0000e+00, -8.1956e-08,
         -2.7567e-07],
        [-2.9802e-08, -3.6322e-08,  1.0431e-07, -8.1956e-08,  1.0000e+00,
         -2.9802e-07],
        [ 1.4901e-08, -1.2247e-07, -1.6391e-07, -2.7567e-07, -2.9802e-07,
          1.0000e+00]])



In [1]:
import torch

# Prosty model liniowy
class SimpleModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(1, 1)
    
    def forward(self, x):
        return self.linear(x)

model = SimpleModel()
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Dane wejściowe i etykiety
x = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[2.0], [4.0], [6.0]])

# Propagacja w przód
output = model(x)
loss = criterion(output, y)

print("Loss before backward:", loss)
print("Gradient of weight before backward:", model.linear.weight.grad)

# Propagacja wsteczna
loss.backward()

print("Gradient of weight after backward:", model.linear.weight.grad)

# Aktualizacja parametrów
optimizer.step()

print("Weight after optimization step:", model.linear.weight)

Loss before backward: tensor(36.4828, grad_fn=<MseLossBackward0>)
Gradient of weight before backward: None
Gradient of weight after backward: tensor([[-26.0845]])
Weight after optimization step: Parameter containing:
tensor([[-0.3291]], requires_grad=True)
